### ISSUE TITLE
tutorials: custom tags for URDF -> SDFormat conversion

### ISSUE THREAD

**Issue by scpeters** [gazebosim/sdf_tutorials#24]
The `//gazebo` tag and `//gazebo/@reference` attribute are used extensively by the URDF to SDFormat converter in libsdformat. There are some documentation and examples of this in the following places on gazebosim.org, and we could consider hosting some of that on sdformat.org:

* http://gazebosim.org/tutorials?tut=ros_urdf&cat=connect_ros
* http://gazebosim.org/tutorials?tut=kinematic_loop

**Comment by azeey** [comment]
This is addressed (maybe partially) by #88

**Comment by scpeters** [comment]
I think #88 provides good coverage
