### ISSUE TITLE
spec: Should fix ambiguities for //inertial/{pose,mass,inertia}

### ISSUE THREAD

**Issue by EricCousineau-TRI** [gazebosim/sdf_tutorials#70]
Ambiguities raised by @mitiguy in email thread. Relates #18

Items:
- [x] Update SDFormat specification
- [x] Update URDF XML specification analogously: http://wiki.ros.org/urdf/XML/link
- ~Fix website rendering for links~

**Comment by EricCousineau-TRI** [comment]
Made changes to URDF as seen here: https://wiki.ros.org/action/diff/urdf/XML/link?action=diff&rev1=76&rev2=77

**Comment by scpeters** [comment]
> Made changes to URDF as seen here: https://wiki.ros.org/action/diff/urdf/XML/link?action=diff&rev1=76&rev2=77

I made a minor to fix to one of your added sentences: https://wiki.ros.org/action/info/urdf/XML/link?action=diff&rev2=78&rev1=77

otherwise it looks good

**Comment by scpeters** [comment]
draft pull request to fix documentation source for sdformat.org

**Comment by scpeters** [comment]
I have merged https://github.com/ignitionrobotics/sdformat/pull/990 and uploaded the revised specification files

http://sdformat.org/spec?ver=1.9&elem=link#link_inertial

I believe the only remaining action item is ensuring that it renders properly on the website

**Comment by mitiguy** [comment]
Thanks Eric and all.   [Nice work](http://sdformat.org/spec?elem=link).  Much appreciated.
